opam-version: "2.0"
name:         "bin"
maintainer:   [ "Romain Calascibetta <romain.calascibetta@gmail.com>" ]
authors:      [ "Romain Calascibetta <romain.calascibetta@gmail.com>" ]
homepage:     "https://git.robur.coop/robur/bstr"
bug-reports:  "https://git.robur.coop/robur/bstr"
dev-repo:     "git+https://github.com/robur-coop/bstr"
doc:          "https://robur-coop.github.io/bstr/"
license:      "MIT"
synopsis:     "A DSL to describe binary formats"

build: [ "dune" "build" "-p" name "-j" jobs ]
run-test: [ "dune" "runtest" "-p" name "-j" jobs ]

depends: [
  "ocaml"         {>= "4.14.0"}
  "dune"          {>= "3.5.0"}
  "bstr"          {= version}
  "crowbar"       {>= "0.2.2" & with-test}
  "wire"          {= "1.3.0" & with-dev-setup}
  "repr"          {with-dev-setup}
  "data-encoding" {with-dev-setup}
  "angstrom"      {with-dev-setup}
  "faraday"       {with-dev-setup}
  "cstruct"       {with-dev-setup}
  "bechamel"      {with-dev-setup}
  "bechamel-js"   {with-dev-setup}
]
x-maintenance-intent: [ "(latest)" ]
