(executable
 (name fuzz)
 (modules fuzz)
 (ocamlopt_flags
  (:standard -afl-instrument))
 (libraries crowbar bstr bin))

(executable
 (name iso)
 (modules iso)
 (ocamlopt_flags
  (:standard -afl-instrument))
 (libraries crowbar bstr bin))

(rule
 (alias runtest)
 (package bin)
 (action
  (run ./fuzz.exe)))

(rule
 (alias runtest)
 (package bin)
 (action
  (run ./iso.exe)))
